### ISSUE TITLE
The inherited members box doesn't work with Epiphany

### ISSUE THREAD

**Issue by matzipan** [Valadoc/valadoc-org#23] opened 2016-10-04 18:12 UTC
On [this](http://www.valadate.org:8000/#!api=dbus-glib-1/DBus.ObjectPath) page, the box which says "All known members inherited from class string" is not expandable in Epiphany. I'm not sure if it's the code faulty, or it's the fault of webkit2gtk.

**Comment by benwaffle** [comment] 2016-10-04 18:20
Works On My Machine™ (arch linux and unmodified epiphany)

**Comment by matzipan** [comment] 2016-10-04 18:21
Really?

**Comment by benwaffle** [comment] 2016-10-04 18:22
right click > inspect element > console

are there any JS errors?

**Comment by matzipan** [comment] 2016-10-04 18:24
TypeError: null is not an object (evaluating '/url[ \t]*\(('(.*)'|"(.*)")\)/.exec (style.backgroundImage)')

toggle_box — main.js:17

**Comment by btkostner** [comment] 2016-10-05 23:45
@matzipan are you testing from master? It should have been fixed with this PR: https://github.com/flobrosch/valadoc-org/pull/59

**Comment by btkostner** [comment] 2016-11-16 04:14
@matzipan can you check this again. Now that we have control over the domain, the site should be up-to-date with master.

**Comment by lewisgoddard** [comment] 2016-11-16 21:29
The link https://valadoc.org/dbus-glib-1/DBus.ObjectPath shows this working as intended.

**Closed** 2016-11-16 21:30 UTC
Labels: Status Confirmed
