### ISSUE TITLE
Docs for GClue

### ISSUE THREAD

**Issue by danrabbit** [Valadoc/valadoc-org#94] opened 2017-04-30 18:39 UTC
Can't seem to find any docs for GeoClue2

**Comment by tintou** [comment] 2018-06-03 14:35
Duplicate of  #155

**Closed by tintou** 2018-06-03 14:35 UTC

**Comment by ZanderBrown** [comment] 2018-06-03 18:35
@tintou , technically it's the other way round but same difference

**Comment by tintou** [comment] 2018-06-03 19:06
yeah, just more comments there
